config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      omniauth_callbacks: 'users/omniauth_callbacks',
      confirmations: 'users/confirmations'
    },
    path: 'auth'

  post '/login', to: 'user_sessions#create'

  get 'user_session/create'

  resources :time_entries

  resources :groups do
    resources :time_entries
  end

  delete '/logout', to: 'user_sessions#destroy'
  get '/signup', to: 'users#new'
  get 'my_time_entries' => 'users#my_time_entries'

  resources :users do
    resources :time_entries
  end

  root to: 'users#my_time_entries'
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user, required: true
  has_many :time_entries
  validates :name, presence: true, uniqueness: true, length: { maximum: 50 }
  default_scope { order(name: :asc) }
  before_save :downcase_name

  private

  def downcase_name
    self.name = name.downcase
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]
  layout 'logged_out', only: %i[show new edit]

  def index
    @groups = Group.all
    render layout: 'application'
  end

  def show; end

  def new
    @group = current_user.groups.build
  end

  def edit; end

  def create
    @group = current_user.groups.build(group_params)

    unless group_params[:icon].nil?
      uploaded_file = Cloudinary::Uploader.upload(group_params[:icon])
      @group.icon = uploaded_file['secure_url']
    end

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, flash: { success: 'Group was successfully created.' } }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, flash: { success: 'Group was successfully updated.' } }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, flash: { success: 'Group was successfully destroyed.' } }
      format.json { head :no_content }
    end
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<div class="row text-center">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: group, local: true, class: 'form') do |form| %>
      <% if group.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>
          <ul>
            <% group.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <div class="gravatar_edit">
          <div class="group-avatar-wrapper">
            <%= image_tag('default.png', alt: "default", class: "gravatar", id: "group-img-prev") %>
          </div>
          <%= button_tag "Upload image", class: "btn btn-default", type: "button", id: "change-img-btn" %>
          <%= form.file_field :icon, placeholder: 'Upload picture', id: "change-img-field", onchange: "changeGroupImg(this);" %>
        </div>
      </div>

      <div class="form-group">
        <div class="field">
          <%= form.label :name %>
          <%= form.text_field :name, class: 'form-control' %>
        </div>
      </div>

      <div class="btn-container bg-second">
        <%= form.submit "Create", class: "btn btn-second"  %>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/_group.html.erb
<li id="group-<%= group.id %>">
  <a href="<%= group_time_entries_path(group) %>">
    <div>
      <%= image_tag group_icon(group), alt: "group icon" %>
    </div>
    <div class="details">
      <div>
        <div><strong><%= group.name.capitalize %></strong></div>
      </div>
      <div>
        <div>Created: <%= group.created_at.strftime("%d %b %Y") %></div>
        <div>By:
          <%= group.user.name %>
        </div>
      </div>
    </div>
  </a>
</li>

app/views/groups/edit.html.erb
<% provide(:title, 'Edit Group') %>
<% provide(:forwarding_url, groups_path) %>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %>

app/views/groups/index.html.erb
<% provide(:title, 'Groups') %>
<p id="notice"><%= notice %></p>

<ul class="index-ul">
  <%= render @groups %>
</ul>

<div class="btn-container bg-second">
  <%= link_to 'Add new', new_group_path, class: 'btn btn-second' %>
</div>

app/views/groups/new.html.erb
<% provide(:title, 'New Group') %>
<% provide(:forwarding_url, groups_path) %>

<div class="container-fluid">
  <%= render 'form', group: @group %>
</div>

app/views/groups/show.html.erb
<% provide(:title, 'Group') %>
<% provide(:forwarding_url, groups_path) %>

<div class="show-container">
  <div class="row text-center group-avatar-wrapper">
    <%= image_tag group_icon(@group), alt: "group icon" %>
  </div>

  <div class="details">
    <div class="row">
      <div class="col-12">
        <strong>Name:</strong>
        <%= @group.name %>
      </div>
    </div>

    <div class="row">
      <div class="col-12">
        <strong>Creator:</strong>
        <%= @group.user.name %>
      </div>
    </div>
  </div>
</div>

<div class="btn-container">
  <%= link_to 'Edit', edit_group_path(@group), class: 'btn btn-green' %>
</div>