config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      omniauth_callbacks: 'users/omniauth_callbacks',
      confirmations: 'users/confirmations'
    },
    path: 'auth'

  post '/login', to: 'user_sessions#create'

  get 'user_session/create'

  resources :time_entries

  resources :groups do
    resources :time_entries
  end

  delete '/logout', to: 'user_sessions#destroy'
  get '/signup', to: 'users#new'
  get 'my_time_entries' => 'users#my_time_entries'

  resources :users do
    resources :time_entries
  end

  root to: 'users#my_time_entries'
end

app/models/time_entry.rb
class TimeEntry < ApplicationRecord
  belongs_to :group, required: false
  belongs_to :author, class_name: 'User', foreign_key: 'author_id', required: true
  validates :name, presence: true, length: { maximum: 50 }
  validates :start_time, presence: true
  validates :end_time, presence: true
  default_scope { order(created_at: :desc) }
  validate :no_overlaping

  private

  def no_overlaping
    return if !start_time.nil? && !end_time.nil? && start_time < end_time

    errors.add(:end_time, "end time can't be equal or less than start_time")
  end
end

app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController
  before_action :set_time_entry, only: %i[show edit update destroy]
  before_action :set_time_entries, only: [:index]
  before_action :set_group_options, only: %i[new edit]
  layout 'logged_out', only: %i[new edit]

  before_action :authenticate_user!

  def index
    @current_user = current_user
  end

  def show; end

  def new
    @time_entry = current_user.time_entries.build
  end

  def edit; end

  def create
    @time_entry = current_user.time_entries.build(time_entry_params)

    respond_to do |format|
      if @time_entry.save
        format.html { redirect_to @time_entry, flash: { success: 'Time entry was successfully created.' } }
        format.json { render :show, status: :created, location: @time_entry }
      else
        @group_options = Group.all.map { |u| [u.name, u.id] }
        format.html { render :new }
        format.json { render json: @time_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @time_entry.update(time_entry_params)
        format.html { redirect_to @time_entry, flash: { success: 'Time entry was successfully updated.' } }
        format.json { render :show, status: :ok, location: @time_entry }
      else
        format.html { render :edit }
        format.json { render json: @time_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @time_entry.destroy
    respond_to do |format|
      format.html { redirect_to time_entries_url, flash: { success: 'Time entry was successfully destroyed.' } }
      format.json { head :no_content }
    end
  end

  private

  def set_time_entry
    @time_entry = TimeEntry.find(params[:id])
  end

  def time_entry_params
    params.require(:time_entry).permit(:name, :start_time, :end_time, :amount, :group_id)
  end

  def set_time_entries
    @time_entries = TimeEntry.all.where('group_id IS NULL').includes(:group, :author)
    @group = Group.find(params[:group_id]) unless params[:group_id].nil?
    @time_entries = @group.time_entries unless @group.nil?
  end

  def set_group_options
    @group_options = Group.all.map { |u| [u.name, u.id] }
  end
end

app/helpers/time_entries_helper.rb
module TimeEntriesHelper
end

app/views/time_entries/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: time_entry, local: true, class: 'form') do |form| %>
      <% if time_entry.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(time_entry.errors.count, "error") %> prohibited this time_entry from being saved:</h2>
          <ul>
            <% time_entry.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :name, 'Description' %>
        <%= form.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :start_time %>
        <%= form.datetime_field :start_time, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :end_time %>
        <%= form.datetime_field :end_time, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :amount %>
        <%= form.text_field :amount, class: 'form-control', value: '00:00:00', disabled: true %>
      </div>

      <div class="form-group">
        <%= form.label :group_id %>
        <%= form.select(:group_id, @group_options, {include_blank: true}, class: 'form-control') %>
      </div>

      <div class="btn-container bg-second">
        <%= form.submit "Create", class: "btn btn-second" %>
      </div>
    <% end %>
</div>

app/views/time_entries/_time_entry.html.erb
<li id="time-entry-<%= time_entry.id %>">
  <a>
    <div>
      <%= image_tag group_icon(time_entry.group), alt: "time entry group" %>
    </div>
    <div class="details">
      <div>
        <div class="text-bold-gray"><%= time_entry.name %></div>
        <div><strong><%= time_entry.amount %></strong></div>
      </div>
      <div>
        <p class="text-middle-gray"><%= time_entry.created_at.strftime("%d %b %Y") %></p>
        <p class="text-middle-gray">Author: <%= time_entry.author.name %></p>
      </div>
    </div>
  </a>
</li>

app/views/time_entries/edit.html.erb
<%= provide(:title, 'Editing Time Entry') %>

<%= render 'form', time_entry: @time_entry %>

app/views/time_entries/index.html.erb
<% provide(:title, 'Time Entries') %>

<ul class="index-ul">
  <%= render @time_entries %>
</ul>

<div class="btn-container">
  <%= link_to 'Add new', new_time_entry_path, class: 'btn btn-green' %>
</div>

app/views/time_entries/new.html.erb
<% provide(:title, 'New Time Entry') %>
<% provide(:forwarding_url, my_time_entries_path) %>

<%= render 'form', time_entry: @time_entry %>

app/views/time_entries/show.html.erb
<% provide(:title, 'Time Entry') %>
<% provide(:forwarding_url, time_entries_path) %>

<div class="show-container">
  <div class="details">
    <div class="row">
      <strong>Description:</strong>
      <%= @time_entry.name %>
    </div>

    <div class="row">
      <strong>Start time:</strong>
      <%= format_datetime(@time_entry.start_time) %>
    </div>

    <div class="row">
      <strong>End time:</strong>
      <%= format_datetime(@time_entry.end_time) %>
    </div>

    <div class="row">
      <strong>Total time:</strong>
      <%= @time_entry.amount %>
    </div>

    <div class="row">
      <strong>Group:</strong>
      <%= @time_entry.group.name unless @time_entry.group.nil?  %>
    </div>

    <div class="row">
      <strong>Author:</strong>
      <%= @time_entry.author.name %>
    </div>
  </div>
</div>

<div class="btn-container">
  <%= link_to 'Edit', edit_time_entry_path(@time_entry), class: 'btn btn-green' %>
</div>

<%= link_to 'Back', time_entries_path %>